version: '3.8' # La versión del formato del archivo

services:
  # 1. Nuestro servicio de Backend
  api-backend:
    build: 
      context: ./backend # Dónde está el código y el Dockerfile
    ports:
      - "3000:3000" # Mapeamos el puerto 3000 de tu PC al 3000 del contenedor
    # Opcional pero recomendado: un nombre claro para el contenedor
    container_name: mi_backend_node 

  # 2. Nuestro servicio de Frontend
  web-frontend:
    build: 
      context: ./frontend # Dónde está el código y el Dockerfile
    ports:
      - "8080:80" # Tu PC en el 8080, Nginx (dentro del contenedor) en el 80
    container_name: mi_frontend_react
    depends_on:
      - api-backend # Le decimos a Docker que levante el backend primero