version: '3.8' # The file format version

services:
  # 1. Our Backend service
  api-backend:
    build: 
      context: ./backend # Where the code and Dockerfile are located
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    # Optional but recommended: a clear, descriptive name for the container
    container_name: my_backend_node 

  # 2. Our Frontend service
  web-frontend:
    build: 
      context: ./frontend # Where the code and Dockerfile are located
    ports:
      - "8080:80" # Host on 8080, Nginx (inside the container) on 80
    container_name: my_frontend_react
    depends_on:
      - api-backend # Tell Docker to start the backend before the frontend